name: Userspace Keymap Build
on: [workflow_dispatch]

jobs:
  build:
    runs_on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        side:
          - left
          - right
        board:
          - a_dux

    steps:
      - name: Disable git safe directory checks
        run: git config --global --add safe.directory '*'

      - name: Checkout QMK
        uses: actions/checkout@v3
        with:
          repository: qmk/qmk_firmware
          submodules: recursive

      - name: Checkout this directory
        uses: actions/checkout@v3
        with:
          path: users/${{ github.actor }}

      - name: Compile
        env:
          side: ${{ matrix.side }}
          board: ${{ matrix.board }}
          path: users/${{ github.actor }}
        run: >
          qmk compile "$path/keymap.json"

      - name: Archive output
        uses: actions/upload-artifact@v3
        with:
          retention-days: 60
          name: ${{ matrix.board }}_${{ matrix.side }}
          path: |
            *.hex
            *.bin
            *.uf2
