name: Userspace Keymap Build
on: [workflow_dispatch]

jobs:
  build:
    runs_on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        keymap:
          - combos

    steps:
      - name: Disable git safe directory checks
        run: git config --global --add safe.directory '*'

      - name: Checkout QMK
        uses: actions/checkout@v3
        with:
          repository: qmk/qmk_firmware
          submodules: recursive

      - name: Checkout this directory
        uses: actions/checkout@v3
        with:
          path: users/${{ github.actor }}

      - name: Compile
        run: >
          qmk compile "users/${{ github.actor }}/keymaps/${{ matrix.keymap }}.json"

      - name: Archive output
        uses: actions/upload-artifact@v3
        with:
          retention-days: 60
          name: ${{ matrix.keymap }}_${{ github.actor }}
          path: |
            *.hex
            *.bin
            *.uf2
